package com.netshoes.dynamicshipping;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class CategoryList implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.util.List<java.lang.String> categoryList;

   public CategoryList()
   {
   }

   public java.util.List<java.lang.String> getCategoryList()
   {
      return this.categoryList;
   }

   public void setCategoryList(java.util.List<java.lang.String> categoryList)
   {
      this.categoryList = categoryList;
   }

   public CategoryList(java.util.List<java.lang.String> categoryList)
   {
      this.categoryList = categoryList;
   }

}