package com.netshoes.dynamicshipping;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Customer implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String customerType;
   private int zipCode;

   public Customer()
   {
   }

   public java.lang.String getCustomerType()
   {
      return this.customerType;
   }

   public void setCustomerType(java.lang.String customerType)
   {
      this.customerType = customerType;
   }

   public int getZipCode()
   {
      return this.zipCode;
   }

   public void setZipCode(int zipCode)
   {
      this.zipCode = zipCode;
   }

   public Customer(java.lang.String customerType, int zipCode)
   {
      this.customerType = customerType;
      this.zipCode = zipCode;
   }

}