package com.netshoes.dynamicshipping;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class DynamicShipping implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public DynamicShipping() {
    }

}