package com.netshoes.dynamicshipping;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Order implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.util.List<com.netshoes.dynamicshipping.Product> products;
   private com.netshoes.dynamicshipping.Customer customer;
   private java.lang.String storeCode;
   private java.math.BigDecimal subtotal;
   private java.math.BigDecimal discount;
   private java.lang.String campaignCode;

   public Order()
   {
   }

   public java.util.List<com.netshoes.dynamicshipping.Product> getProducts()
   {
      return this.products;
   }

   public void setProducts(
         java.util.List<com.netshoes.dynamicshipping.Product> products)
   {
      this.products = products;
   }

   public com.netshoes.dynamicshipping.Customer getCustomer()
   {
      return this.customer;
   }

   public void setCustomer(com.netshoes.dynamicshipping.Customer customer)
   {
      this.customer = customer;
   }

   public java.lang.String getStoreCode()
   {
      return this.storeCode;
   }

   public void setStoreCode(java.lang.String storeCode)
   {
      this.storeCode = storeCode;
   }

   public java.math.BigDecimal getSubtotal()
   {
      return this.subtotal;
   }

   public void setSubtotal(java.math.BigDecimal subtotal)
   {
      this.subtotal = subtotal;
   }

   public java.math.BigDecimal getDiscount()
   {
      return this.discount;
   }

   public void setDiscount(java.math.BigDecimal discount)
   {
      this.discount = discount;
   }

   public java.lang.String getCampaignCode()
   {
      return this.campaignCode;
   }

   public void setCampaignCode(java.lang.String campaignCode)
   {
      this.campaignCode = campaignCode;
   }

   public Order(java.util.List<com.netshoes.dynamicshipping.Product> products,
         com.netshoes.dynamicshipping.Customer customer,
         java.lang.String storeCode, java.math.BigDecimal subtotal,
         java.math.BigDecimal discount, java.lang.String campaignCode)
   {
      this.products = products;
      this.customer = customer;
      this.storeCode = storeCode;
      this.subtotal = subtotal;
      this.discount = discount;
      this.campaignCode = campaignCode;
   }

}