package com.netshoes.dynamicshipping;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Product implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String skuCode;
   private int quantity;
   private int weight;
   private java.math.BigDecimal price;
   private java.math.BigDecimal discount;
   private java.lang.String categoryCode;
   private java.lang.String subCategoryCode;

   public Product()
   {
   }

   public java.lang.String getSkuCode()
   {
      return this.skuCode;
   }

   public void setSkuCode(java.lang.String skuCode)
   {
      this.skuCode = skuCode;
   }

   public int getQuantity()
   {
      return this.quantity;
   }

   public void setQuantity(int quantity)
   {
      this.quantity = quantity;
   }

   public int getWeight()
   {
      return this.weight;
   }

   public void setWeight(int weight)
   {
      this.weight = weight;
   }

   public java.math.BigDecimal getPrice()
   {
      return this.price;
   }

   public void setPrice(java.math.BigDecimal price)
   {
      this.price = price;
   }

   public java.math.BigDecimal getDiscount()
   {
      return this.discount;
   }

   public void setDiscount(java.math.BigDecimal discount)
   {
      this.discount = discount;
   }

   public java.lang.String getCategoryCode()
   {
      return this.categoryCode;
   }

   public void setCategoryCode(java.lang.String categoryCode)
   {
      this.categoryCode = categoryCode;
   }

   public java.lang.String getSubCategoryCode()
   {
      return this.subCategoryCode;
   }

   public void setSubCategoryCode(java.lang.String subCategoryCode)
   {
      this.subCategoryCode = subCategoryCode;
   }

   public Product(java.lang.String skuCode, int quantity, int weight,
         java.math.BigDecimal price, java.math.BigDecimal discount,
         java.lang.String categoryCode, java.lang.String subCategoryCode)
   {
      this.skuCode = skuCode;
      this.quantity = quantity;
      this.weight = weight;
      this.price = price;
      this.discount = discount;
      this.categoryCode = categoryCode;
      this.subCategoryCode = subCategoryCode;
   }

}