package com.netshoes.dynamicshipping;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class SkuList implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.util.List<java.lang.String> skuList;

   public SkuList()
   {
   }

   public java.util.List<java.lang.String> getSkuList()
   {
      return this.skuList;
   }

   public void setSkuList(java.util.List<java.lang.String> skuList)
   {
      this.skuList = skuList;
   }

   public SkuList(java.util.List<java.lang.String> skuList)
   {
      this.skuList = skuList;
   }

}