package com.netshoes.dynamicshipping;

rule "SKU não eligível a promoção"
salience 10
	when
		$result : DynamicShipping(eligibleFreeShipping == true)
		$order : Order()
		$item : Product() from $order.products
		//SkuList(skuList contains $item.getSkuCode())
	then
		System.out.println("SKU não eligível a promoções de frete: " + $item.getSkuCode());
		modify($result) {
			setEligibleFreeShipping(false),
			setEligibleDiscount(true),
			setEligibleOvercharge(true);
		}
end

rule "Categoria não eligível a promoção"
salience 10
	when
		$result : DynamicShipping(eligibleFreeShipping == true)
		$order : Order()
		$item : Product() from $order.products
		//CategoryList(categoryList contains $item.getCategoryCode())
	then
		System.out.println("Categoria não eligível a promoção: " + $item.getCategoryCode());
		modify($result) {
			setEligibleFreeShipping(false),
			setEligibleDiscount(true),
			setEligibleOvercharge(true);
		}
end
